# repository: https://github.com/Canop/bacon
# docs: https://dystroy.org/bacon/config/

default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = [
    "cargo",
    "check",
    "--all-features",
    "--all-targets",
    "--color",
    "always",
]
need_stdout = false
watch = ["benches", "examples", "tests"]

[jobs.clippy]
command = [
    "cargo",
    "clippy",
    "--all-features",
    "--all-targets",
    "--color",
    "always",
]
need_stdout = false
watch = ["benches", "examples", "tests"]

[jobs.cranky]
command = [
    "cargo",
    "cranky",
    "--all-features",
    "--all-targets",
    "--color",
    "always",
]
need_stdout = false
watch = ["benches", "examples", "tests"]

[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true
watch = ["tests"]

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true
watch = ["tests"]

[jobs.test-all]
command = [
    "cargo",
    "test",
    "--all-features",
    "--all-targets",
    "--color",
    "always",
]
need_stdout = true
watch = ["tests"]

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"

[keybindings]
a = "job:check-all"
c = "job:cranky"
d = "job:doc-open"
i = "job:initial"
n = "job:nextest"
t = "job:test"
