numbered_command = false

use_trash = true
watch_files = true
xdg_open = true
xdg_open_fork = true

[display]
# default, hsplit
mode = "default"

column_ratio = [1, 2, 2]
scroll_offset = 6

show_borders = true
show_hidden = false
show_icons = true

automatically_count_files = false
collapse_preview = true
line_number_style = "none"
tilde_in_titlebar = true

[display.sort]
# lexical, mtime, natural
method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 2097152 # 2MB
# preview_script = "~/.config/joshuto/preview_file.sh"

[tab]
# inherit, home, root
home_page = "inherit"
