#!/usr/bin/env sh

# alias-custom.sh
# ===============

alias c="code"
alias k="kdevelop"

alias shell="konsole"
alias term="terminator"
alias term-proj="term -l proj"
alias term-work="term -l work"

alias g="git"
alias ga="g a"
alias gaa="g aa"
alias gai="g ai"
alias gass="g assume"
alias gassa="g assume-all"
alias gau="g au"
alias gbr="g br"
alias gbrc="g brc"
alias gbrm="g brm"
alias gc="g c"
alias gca="g ca"
alias gcb="g cb"
alias gcm="g cm"
alias gcp="g cp"
alias gco="g co"
alias gd="g d"
alias gdc="g dc"
alias gdcs="g dcs"
alias gds="g ds"
alias gfl="g fl"
alias gl="g l"
alias gll="g ll"
alias gr="g r"
alias grbi="g rbi"
alias grbi5="g rbi5"
alias grbi10="g rbi10"
alias gsh="g sh"
alias gsha="g sha"
alias gsha@="g shaat"
alias gshiu="g shiu"
alias gshw="g shw"
alias gshw@="g shwat"
alias gst="g s"
alias gsts="g ss"
alias guass="g unassume"
alias guassa="g unassume-all"

alias svnr="svn rebase"
alias svnd="svn dcommit"
alias svnl="svn log --oneline --show-commit"

alias y="yarn"
alias ycl="yarn clean"
alias yi="yarn install"
alias ycli="yarn clean:install"
alias yw="yarn workspace"
alias ywl="yarn workspaces list"
alias ywlj="yarn workspaces list --json"
alias yw@g="yarn workspace @goldeimer/"
